django_basic/conf/urls.py
from django.contrib import admin
from django.urls import include, path
 
urlpatterns = [
    path('', include('contacts.urls')),
    path('admin/', admin.site.urls),
]

django_basic/crud/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
 
app_name = 'crud'
urlpatterns = [
    path('goods_create/', login_required(views.GoodsCreate.as_view()), name='goods_create'),
]

django_basic/crud/models.py
from django.db import models
from django.core.validators import MaxValueValidator
 
class Goods(models.Model):
    name = models.CharField('商品名', unique=True, max_length=10, null=True)
    management_code = models.CharField('管理コード', unique=True, max_length=20)
    price = models.PositiveIntegerField('価格', validators=[MaxValueValidator(1000000000)])
    release_date = models.DateField('発売日', blank=True, null=True)
    release_flag = models.BooleanField('発売済み', default=False)
    description = models.CharField('商品説明', max_length=100000)
    image = models.ImageField('商品画像', null=True, blank=True, upload_to='goods_images/')
    state_flag = models.BooleanField('運用状況', default=True)

    def __str__(self):
        return self.name

django_basic/crud/forms.py
from django import forms
from .models import Goods
 
class GoodsCreateForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ('name', 'management_code', 'price', 'release_date', 'release_flag', 'description', 'image')

django_basic/crud/views.py
from django.views import generic
from .models import Goods
from .forms import GoodsCreateForm
 
class GoodsCreate(generic.CreateView):
    form_class = GoodsCreateForm
    template_name = 'crud/goods_create.html'
    success_url = '/crud/goods_create'
 
class GoodsList(generic.ListView):
    model = Goods
    template_name = 'crud/goods_list.html'
 
class GoodsDelete(generic.DeleteView):
    model = Goods
    template_name = 'crud/goods_delete.html'

django_basic/templates/crud/goods_create.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品作成ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="作成">
</form>
 
{% endblock %}

django_basic/templates/crud/goods_list.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品リスト
<a href="{% url 'crud:goods_create' %}">作成</a>
{% for goods in goods_list %}
  {% if goods.state_flag %}
    <p>{{ goods.name }}/<a href="{% url 'crud:goods_detail' goods.id %}">詳細</a></p>
  {% endif %}
{% endfor %}
 
{% endblock %}